// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtcchttcvmaijvjjcxpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y2NodHRjdm1haWp2ampjeHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2OTM2MzcsImV4cCI6MjA0NzI2OTYzN30.nXX3e8TPfHwJZvtffI4XzA9um7v8Rp_9uhHtZSVtW5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);